### ISSUE TITLE
KeyError when running OutputTranscriptInfo

### ISSUE THREAD

**Issue by yeroslaviz** [xryanglab/RiboMiner#10]
When running the `OutputTranscriptInfo` script I get the following error:

```
$ OutputTranscriptInfo -c riboMiner/RiboCode_annot/transcripts_cds.txt -g $gtf -f $fa -o riboMiner/longest.transcripts.info.txt -O riboMiner/all.transcripts.info.txt
Starting outputing longest trans...
Traceback (most recent call last):
  File "/fs/home/yeroslaviz/miniconda3/envs/ribominer/bin/OutputTranscriptInfo", line 10, in <module>
    sys.exit(main())
  File "/fs/home/yeroslaviz/miniconda3/envs/ribominer/lib/python3.9/site-packages/RiboMiner/OutputTranscriptInfo.py", line 38, in main
    get_longest_transcripts_information(options.coorFile,options.transcriptFile,options.gtfFile,options.longestTransInfo)
  File "/fs/home/yeroslaviz/miniconda3/envs/ribominer/lib/python3.9/site-packages/RiboMiner/FunctionDefinition.py", line 123, in get_longest_transcripts_information
    tmp = sorted(list(trans_id),key=lambda x: transLengthDict[x])[-1]
  File "/fs/home/yeroslaviz/miniconda3/envs/ribominer/lib/python3.9/site-packages/RiboMiner/FunctionDefinition.py", line 123, in <lambda>
    tmp = sorted(list(trans_id),key=lambda x: transLengthDict[x])[-1]
KeyError: 'T11F9.4b.1'
```

The key referred by the error is the transcript name from C. elegans. it is the second transcript in both the `transcripts_cds.txt` and the `transcripts_cds.fa` files. 

```
$ head riboMiner/RiboCode_annot/*.{fa,txt}
==> riboMiner/RiboCode_annot/transcripts_sequence.fa <==
>F07C3.7.1 1738
ACGCAAAAATGAACGAAAAAGAAGAAGAAGTATCGCTGAATCAGATCAAGCTCAAGCCACGTATTTCACTTTTCAATGGCTGCACAATCATTATCGGAGTTA...
>T11F9.4a.1 1750
GTTTATGATGTTTTCATTCCGATGAACACATTTTCTTTATTTGTTTCCGTTCTAATTGTCGAGTCATGCTGAATGTTTTTGGAGTCTCCGCAAGTATGCCCGATGAC...
...

==> riboMiner/RiboCode_annot/transcripts_cds.txt <==
F07C3.7.1       9       1460
T11F9.4a.1      66      1637
...
```

any ideas why I have this error?

thanks

Assa

**Comment by sherkinglee** [comment]
Hi Assa,
Thanks for your interest in RiboMiner! Could you tell me what version of the genome reference you are using? In my case, the reference is "Caenorhabditis_elegans.WBcel235.94” downloaded from Ensemble. And I did not encounter the problem you proposed. Here are my results:

```
OutputTranscriptInfo -c RiboCode_annot/transcripts_cds.txt -g Caenorhabditis_elegans.WBcel235.94.gtf -f RiboCode_annot/transcripts_sequence.fa -o longest.transcripts.info.txt -O all.transcripts.info.txt
Starting outputting longest trans...
20222  transcripts will be used in the follow analysis.

Finishing!
Starting outputting all trans...
Finishing!
``` 
And the version of RiboMiner I used was the latest one deposed on the GitHub page.

Best wishes,
Fajin
