### ISSUE TITLE
DuplicateHeaderException' from 'pyfasta' in prepare_transcripts

### ISSUE THREAD

**Issue by nitishkumarmishra** [xryanglab/RiboMiner#11]
Hi,
I am trying to use RiboMiner, I feel there is some issue with "pyfasta". I don't think there is any function 'DuplicateHeaderException' in pyfasta. I am not sure how I can use it, here is my command and error-

prepare_transcripts -g Mus_musculus.GRCm39.104.rdna_rn18s.gtf -f prepare_transcripts -g Mus_musculus.GRCm39.dna.primary_assembly.rdna.fa -o RiboMiner_out

Traceback (most recent call last):
  File "/home/nmishra/.conda/envs/RiboMiner/bin/prepare_transcripts", line 33, in <module>
    sys.exit(load_entry_point('RiboCode==1.2.10', 'console_scripts', 'prepare_transcripts')())
  File "/home/nmishra/.conda/envs/RiboMiner/bin/prepare_transcripts", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/nmishra/.conda/envs/RiboMiner/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 209, in load
    module = import_module(match.group('module'))
  File "/home/nmishra/.conda/envs/RiboMiner/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nmishra/.conda/envs/RiboMiner/lib/python3.7/site-packages/RiboCode/prepare_transcripts.py", line 17, in <module>
    from pyfasta import Fasta
  File "/home/nmishra/.conda/envs/RiboMiner/lib/python3.7/site-packages/pyfasta/__init__.py", line 4, in <module>
    from pyfasta import DuplicateHeaderException
ImportError: cannot import name 'DuplicateHeaderException' from 'pyfasta' (/home/nmishra/.conda/envs/RiboMiner/lib/python3.7/site-packages/pyfasta/__init__.py)

**Comment by sherkinglee** [comment]
Hi,
Thanks for your question! It seems that this is not a problem of RiboMiner itself but a problem in RiboCode. Please refer to https://github.com/xryanglab/RiboCode/issues/53 for your answers. Specifically, you may solve it by uninstalling fasta and pyfasta and re-install them.

Best wishes,
Sherking

**Comment by erlun1** [comment]
RiboCode uses pyfasta instead of the updated version pyfaidx, so I browsed through the source code of pyfasta and found that in the _init_.py file, the code from fasta import Fasta, complement, DuplicateHeaderException is actually intended to call the fasta.py script in the same directory, rather than importing a module named fasta. If necessary, you can manually modify the _init_.py file and then install it.

**Comment by erlun1** [comment]
additionally,"pyfasta" requires Python 2, while "RiboCode" requires Python 3.6 or above.So:
In fasta.py, for Python 3.10 and above, from collections import Mapping should be changed to from collections.abc import Mapping.
In records.py, for Python 3.X, import cPickle should be changed to import _pickle as cPickle, and the long type should be removed.
In split_fasta.py, for Python 3.X, from cStringIO import StringIO should be changed to from io import StringIO.

**Comment by sherkinglee** [comment]
Thanks for your suggestions. We will check for that later on. @zhengtaoxiao @YangLabProject

**Comment by seeninheoi** [comment]
> Hi, Thanks for your question! It seems that this is not a problem of RiboMiner itself but a problem in RiboCode. Please refer to [xryanglab/RiboCode#53](https://github.com/xryanglab/RiboCode/issues/53) for your answers. Specifically, you may solve it by uninstalling fasta and pyfasta and re-install them.
> 
> Best wishes, Sherking

It doesn't work after re-install┭┮﹏┭┮
