### ISSUE TITLE
Periodicity

### ISSUE THREAD

**Issue by whildencm** [xryanglab/RiboMiner#14]
Hi, 
I commented this on a closed issue a bit ago, but want to post it here in case it wasn't seen. It is an error with running 'periodicity'.

 I have run into the same error as the user above. I have tried installing Ribominer 3 different ways, including the way you describe above, and have tried in both python 3.7, 3.8, and 3.10. Do you have any other ideas on how to fix this? This is the last thing I need to do for my analysis so I am desperate for help haha.

Input:
Periodicity -i $file \ -a /n/XXXX/share_root/Users/XXXX/cmw_expt56/20231102_ORFsbyCond/RiboCode_annot \ -o $base"_WT_OnlyTrs" \ -c /n/XXXX/share_root/Users/XXXX/cmw_expt56/20231018_RiboMiner_Ctx/longest.transcripts.info.txt \ -L 29 -R 36 \ -S wt_only_trs.txt --id-type transcript_id

Error:

`21741 transcripts will be used in the follow analysis.

There are 997 transcripts from wt_only_trs.txt used for following analysis.
There are 997 transcripts with both start and stop codon will be used for following analysis.
Start calculating read density...
There are 997 used for statistics.
Traceback (most recent call last):
File "/n/home01/XXXXX/.conda/envs/RPF_env_2024/bin/Periodicity", line 33, in
sys.exit(load_entry_point('RiboMiner==0.2.3.2', 'console_scripts', 'Periodicity')())
File "/n/home01/XXXX/.conda/envs/RPF_env_2024/lib/python3.7/site-packages/RiboMiner-0.2.3.2-py3.7.egg/RiboMiner/Periodicity.py", line 169, in main
File "/n/home01/XXXXX/.conda/envs/RPF_env_2024/lib/python3.7/site-packages/RiboMiner-0.2.3.2-py3.7.egg/RiboMiner/Periodicity.py", line 82, in plot_periodicity_start_codon
File "/n/home01/XXXXX/.conda/envs/RPF_env_2024/lib/python3.7/site-packages/matplotlib/init.py", line 1414, in inner
return func(ax, *map(sanitize_sequence, args), **kwargs)
File "/n/home01/XXXX/.conda/envs/RPF_env_2024/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 1135, in vlines
masked_verts[:, 1, 1] = ymax
File "/n/home01/XXXX/.conda/envs/RPF_env_2024/lib/python3.7/site-packages/numpy/ma/core.py", line 3379, in setitem
_data[indx] = dval
ValueError: could not broadcast input array from shape (102,) into shape (101,)`

**Comment by sherkinglee** [comment]
Hi,
Thanks for using RiboMiner! I did not encounter this before, but Pormr seems to have fixed it by modifying the Periodicity.py script in RiboMiner like:
```
before: y1=start_density.loc[:,L]
after: y1=start_density.loc[:,L][:-1]
```
I have not checked it yet, but you can try for it first and re-install the package. And I will update it once I'm ready for the next version!

best wishes,
Sherking

**Comment by whildencm** [comment]
It worked beautifully- thank you!!

**Comment by NastiaSkuba** [comment]
Hello! 
I faced the same issue as above, and after modifying the Periodicity.py file, I could obtain the start codon files at least, but the stop codon did not work. 
A similar issue appeared when I used the ORFik package. I assume it is because I have some UTRs annotated shorter than 30 nt. Can you help solve it somehow?
