### ISSUE TITLE
Error in Periodicity

### ISSUE THREAD

**Issue by lbwfff** [xryanglab/RiboMiner#5]
Hi,
Thanks for providing excellent tools, I ran into some troubles in the process of running. The following are my parameters：
`Periodicity -i SRR6026774.Aligned.toTranscriptome.out.sorted.bam -a GRCh38 -o SRR6026774 -c longest.transcripts.info.txt -L 25 -R 35`
The following is the error message：
```
	Loading transcripts.pickle ...
19690  transcripts will be used in the follow analysis.

There are 19690 transcripts with both start and stop codon will be used for following analysis.
Start calculating read density...
There are 19690 used for statistics.
Traceback (most recent call last):
  File "/home/huangwx/miniconda3/envs/ribominer/bin/Periodicity", line 10, in <module>
    sys.exit(main())
  File "/home/huangwx/miniconda3/envs/ribominer/lib/python3.7/site-packages/RiboMiner/Periodicity.py", line 169, in main
    plot_periodicity_start_codon(start_density,specific_counts,options.output_prefix)
  File "/home/huangwx/miniconda3/envs/ribominer/lib/python3.7/site-packages/RiboMiner/Periodicity.py", line 82, in plot_periodicity_start_codon
    ax1.vlines(x,ymin=np.zeros(101),ymax=y1,colors=colors[:-1],linewidth=2)
  File "/home/huangwx/miniconda3/envs/ribominer/lib/python3.7/site-packages/matplotlib/__init__.py", line 1361, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/huangwx/miniconda3/envs/ribominer/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 1115, in vlines
    masked_verts[:, 1, 1] = ymax
  File "/home/huangwx/miniconda3/envs/ribominer/lib/python3.7/site-packages/numpy/ma/core.py", line 3379, in __setitem__
    _data[indx] = dval
ValueError: could not broadcast input array from shape (102,) into shape (101,)
```
Why is there such an error and how can I solve this problem?
Thanks，
LeeLee

**Comment by sherkinglee** [comment]
Hi, 
Thanks for your interest in RiboMiner. I have analyzed this dataset before and I do not encounter this error. Here is my code and results:
```
(base) [lifj@login01 08.periodicity]$ Periodicity -i ../07.STAR/SRR6026774_STAR/SRR6026774.Aligned.toTranscriptome.out.sorted.bam -a ~/lifj/data/Reference/human/RiboCode_annot_Human/RiboCode_annot/ -o SRR6026774 -c ~/lifj/data/Reference/human/longest.transcripts.info.txt -L 25 -R 35
        Loading transcripts.pickle ...
19636  transcripts will be used in the follow analysis.

There are 19636 transcripts with both start and stop codon will be used for following analysis.
Start calculating read density...
There are 19636 used for statistics.
findfont: Font family ['Arial'] not found. Falling back to DejaVu Sans.
Finish the step of plot periodicity
```
The version of my RiboMiner is 0.2.3.2 and I suggest that you can download the RiboMiner package from the GitHub (https://github.com/xryanglab/RiboMiner) and re-install it with:
```
cd RiboMiner
python setup.py install

```
And if you have any other questions after that, please feel free to contact me.

Best,
Sherking

**Comment by cmichellew** [comment]
Hello,  I have run into the same error as the user above. I have tried installing Ribominer 3 different ways, including the way you describe above, and have tried in both python 3.7, 3.8, and 3.10. Do you have any other ideas on how to fix this? This is the last thing I need to do for my analysis so I am desperate for help haha.

Input:
`Periodicity -i $file \
    -a /n/whipple_lab/share_root/Users/cwhilden/cmw_expt56/20231102_ORFsbyCond/RiboCode_annot \
    -o $base"_WT_OnlyTrs" \
    -c /n/whipple_lab/share_root/Users/cwhilden/cmw_expt56/20231018_RiboMiner_Ctx/longest.transcripts.info.txt \
    -L 29 -R 36 \
    -S wt_only_trs.txt --id-type transcript_id`

Error:
```
`21741  transcripts will be used in the follow analysis.

There are 997 transcripts from wt_only_trs.txt used for following analysis.
There are 997 transcripts with both start and stop codon will be used for following analysis.
Start calculating read density...
There are 997 used for statistics.
Traceback (most recent call last):
  File "/n/home01/cwhilden/.conda/envs/RPF_env_2024/bin/Periodicity", line 33, in <module>
    sys.exit(load_entry_point('RiboMiner==0.2.3.2', 'console_scripts', 'Periodicity')())
  File "/n/home01/cwhilden/.conda/envs/RPF_env_2024/lib/python3.7/site-packages/RiboMiner-0.2.3.2-py3.7.egg/RiboMiner/Periodicity.py", line 169, in main
  File "/n/home01/cwhilden/.conda/envs/RPF_env_2024/lib/python3.7/site-packages/RiboMiner-0.2.3.2-py3.7.egg/RiboMiner/Periodicity.py", line 82, in plot_periodicity_start_codon
  File "/n/home01/cwhilden/.conda/envs/RPF_env_2024/lib/python3.7/site-packages/matplotlib/__init__.py", line 1414, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/n/home01/cwhilden/.conda/envs/RPF_env_2024/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 1135, in vlines
    masked_verts[:, 1, 1] = ymax
  File "/n/home01/cwhilden/.conda/envs/RPF_env_2024/lib/python3.7/site-packages/numpy/ma/core.py", line 3379, in __setitem__
    _data[indx] = dval
ValueError: could not broadcast input array from shape (102,) into shape (101,)`
```

**Comment by whildencm** [comment]
Hello, I have run into the same error as the user above. I have tried installing Ribominer 3 different ways, including the way you describe above, and have tried in both python 3.7, 3.8, and 3.10. Do you have any other ideas on how to fix this? This is the last thing I need to do for my analysis so I am desperate for help haha.

Input:
Periodicity -i $file \ -a /n/XXXX/share_root/Users/XXXX/cmw_expt56/20231102_ORFsbyCond/RiboCode_annot \ -o $base"_WT_OnlyTrs" \ -c /n/XXXX/share_root/Users/XXXX/cmw_expt56/20231018_RiboMiner_Ctx/longest.transcripts.info.txt \ -L 29 -R 36 \ -S wt_only_trs.txt --id-type transcript_id

Error:

`21741  transcripts will be used in the follow analysis.

There are 997 transcripts from wt_only_trs.txt used for following analysis.
There are 997 transcripts with both start and stop codon will be used for following analysis.
Start calculating read density...
There are 997 used for statistics.
Traceback (most recent call last):
  File "/n/home01/XXXXX/.conda/envs/RPF_env_2024/bin/Periodicity", line 33, in <module>
    sys.exit(load_entry_point('RiboMiner==0.2.3.2', 'console_scripts', 'Periodicity')())
  File "/n/home01/XXXX/.conda/envs/RPF_env_2024/lib/python3.7/site-packages/RiboMiner-0.2.3.2-py3.7.egg/RiboMiner/Periodicity.py", line 169, in main
  File "/n/home01/XXXXX/.conda/envs/RPF_env_2024/lib/python3.7/site-packages/RiboMiner-0.2.3.2-py3.7.egg/RiboMiner/Periodicity.py", line 82, in plot_periodicity_start_codon
  File "/n/home01/XXXXX/.conda/envs/RPF_env_2024/lib/python3.7/site-packages/matplotlib/__init__.py", line 1414, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/n/home01/XXXX/.conda/envs/RPF_env_2024/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 1135, in vlines
    masked_verts[:, 1, 1] = ymax
  File "/n/home01/XXXX/.conda/envs/RPF_env_2024/lib/python3.7/site-packages/numpy/ma/core.py", line 3379, in __setitem__
    _data[indx] = dval
ValueError: could not broadcast input array from shape (102,) into shape (101,)`
